// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAZb-u2yD0nI1a6URMSW3Bl4nJpwCZ-tyA',
    appId: '1:748948382935:web:6213426f93e88eb6d93c92',
    messagingSenderId: '748948382935',
    projectId: 'phoneauth-a99a5',
    authDomain: 'phoneauth-a99a5.firebaseapp.com',
    storageBucket: 'phoneauth-a99a5.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDckr273DH5jYXIHvYcvyBzh3JzIj1-9fQ',
    appId: '1:748948382935:android:0146c80c42cdeda6d93c92',
    messagingSenderId: '748948382935',
    projectId: 'phoneauth-a99a5',
    storageBucket: 'phoneauth-a99a5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDafd0DszM4lCvlpIrjG2GFGKfIEUBaUxQ',
    appId: '1:748948382935:ios:e4de909833ff7938d93c92',
    messagingSenderId: '748948382935',
    projectId: 'phoneauth-a99a5',
    storageBucket: 'phoneauth-a99a5.appspot.com',
    androidClientId: '748948382935-m8qt87m5pj7dv3ulv9o5du2p0q4i2eiu.apps.googleusercontent.com',
    iosClientId: '748948382935-3c5ip6d4efk8u73tugohdt4fc4tle7vc.apps.googleusercontent.com',
    iosBundleId: 'com.example.phoneBloc',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDafd0DszM4lCvlpIrjG2GFGKfIEUBaUxQ',
    appId: '1:748948382935:ios:e4de909833ff7938d93c92',
    messagingSenderId: '748948382935',
    projectId: 'phoneauth-a99a5',
    storageBucket: 'phoneauth-a99a5.appspot.com',
    androidClientId: '748948382935-m8qt87m5pj7dv3ulv9o5du2p0q4i2eiu.apps.googleusercontent.com',
    iosClientId: '748948382935-3c5ip6d4efk8u73tugohdt4fc4tle7vc.apps.googleusercontent.com',
    iosBundleId: 'com.example.phoneBloc',
  );
}
